# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfsha/_vendor/etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dfsha/_vendor/etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfsha._vendor.gogoproto import gogo_pb2 as dfsha_dot___vendor_dot_gogoproto_dot_gogo__pb2
from dfsha._vendor.etcd.api.etcdserverpb import rpc_pb2 as dfsha_dot___vendor_dot_etcd_dot_api_dot_etcdserverpb_dot_rpc__pb2
from dfsha._vendor.google.api import annotations_pb2 as dfsha_dot___vendor_dot_google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEdfsha/_vendor/etcd/server/etcdserver/api/v3lock/v3lockpb/v3lock.proto\x12\x08v3lockpb\x1a\"dfsha/_vendor/gogoproto/gogo.proto\x1a-dfsha/_vendor/etcd/api/etcdserverpb/rpc.proto\x1a*dfsha/_vendor/google/api/annotations.proto\"*\n\x0bLockRequest\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05lease\x18\x02 \x01(\x03\"I\n\x0cLockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"\x1c\n\rUnlockRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\">\n\x0eUnlockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader2\xb0\x01\n\x04Lock\x12O\n\x04Lock\x12\x15.v3lockpb.LockRequest\x1a\x16.v3lockpb.LockResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/v3/lock/lock:\x01*\x12W\n\x06Unlock\x12\x17.v3lockpb.UnlockRequest\x1a\x18.v3lockpb.UnlockResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/v3/lock/unlock:\x01*BBZ8go.etcd.io/etcd/server/v3/etcdserver/api/v3lock/v3lockpb\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfsha._vendor.etcd.server.etcdserver.api.v3lock.v3lockpb.v3lock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8go.etcd.io/etcd/server/v3/etcdserver/api/v3lock/v3lockpb\310\342\036\001\320\342\036\001'
  _globals['_LOCK'].methods_by_name['Lock']._loaded_options = None
  _globals['_LOCK'].methods_by_name['Lock']._serialized_options = b'\202\323\344\223\002\022\"\r/v3/lock/lock:\001*'
  _globals['_LOCK'].methods_by_name['Unlock']._loaded_options = None
  _globals['_LOCK'].methods_by_name['Unlock']._serialized_options = b'\202\323\344\223\002\024\"\017/v3/lock/unlock:\001*'
  _globals['_LOCKREQUEST']._serialized_start=210
  _globals['_LOCKREQUEST']._serialized_end=252
  _globals['_LOCKRESPONSE']._serialized_start=254
  _globals['_LOCKRESPONSE']._serialized_end=327
  _globals['_UNLOCKREQUEST']._serialized_start=329
  _globals['_UNLOCKREQUEST']._serialized_end=357
  _globals['_UNLOCKRESPONSE']._serialized_start=359
  _globals['_UNLOCKRESPONSE']._serialized_end=421
  _globals['_LOCK']._serialized_start=424
  _globals['_LOCK']._serialized_end=600
# @@protoc_insertion_point(module_scope)
