# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2
from dfsha.v1 import control_pb2 as dfsha_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UploadServiceStub:
    """Solo metadatos. Los bytes de send/receive/read/write pertenecen a BlockService.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginUpload = channel.unary_unary(
                '/dfsha.v1.UploadService/BeginUpload',
                request_serializer=dfsha_dot_v1_dot_control__pb2.BeginUploadRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.UploadPlan.FromString,
                _registered_method=True)
        self.AllocateBlocks = channel.unary_unary(
                '/dfsha.v1.UploadService/AllocateBlocks',
                request_serializer=dfsha_dot_v1_dot_control__pb2.AllocateBlocksRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.BlockPlan.FromString,
                _registered_method=True)
        self.StageManifestPage = channel.unary_unary(
                '/dfsha.v1.UploadService/StageManifestPage',
                request_serializer=dfsha_dot_v1_dot_control__pb2.StageManifestPageRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.PageReceipt.FromString,
                _registered_method=True)
        self.SealManifest = channel.unary_unary(
                '/dfsha.v1.UploadService/SealManifest',
                request_serializer=dfsha_dot_v1_dot_control__pb2.SealManifestRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.PageReceipt.FromString,
                _registered_method=True)
        self.CommitUpload = channel.unary_unary(
                '/dfsha.v1.UploadService/CommitUpload',
                request_serializer=dfsha_dot_v1_dot_control__pb2.CommitUploadRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.CommitResult.FromString,
                _registered_method=True)
        self.AbortUpload = channel.unary_unary(
                '/dfsha.v1.UploadService/AbortUpload',
                request_serializer=dfsha_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/dfsha.v1.UploadService/GetOperation',
                request_serializer=dfsha_dot_v1_dot_control__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.OperationStatus.FromString,
                _registered_method=True)


class UploadServiceServicer:
    """Solo metadatos. Los bytes de send/receive/read/write pertenecen a BlockService.
    """

    def BeginUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StageManifestPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SealManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginUpload,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.BeginUploadRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.UploadPlan.SerializeToString,
            ),
            'AllocateBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateBlocks,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.AllocateBlocksRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.BlockPlan.SerializeToString,
            ),
            'StageManifestPage': grpc.unary_unary_rpc_method_handler(
                    servicer.StageManifestPage,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.StageManifestPageRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.PageReceipt.SerializeToString,
            ),
            'SealManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.SealManifest,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.SealManifestRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.PageReceipt.SerializeToString,
            ),
            'CommitUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitUpload,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.CommitUploadRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.CommitResult.SerializeToString,
            ),
            'AbortUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortUpload,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.OperationRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.GetOperationRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.UploadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UploadService:
    """Solo metadatos. Los bytes de send/receive/read/write pertenecen a BlockService.
    """

    @staticmethod
    def BeginUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/BeginUpload',
            dfsha_dot_v1_dot_control__pb2.BeginUploadRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.UploadPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/AllocateBlocks',
            dfsha_dot_v1_dot_control__pb2.AllocateBlocksRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.BlockPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StageManifestPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/StageManifestPage',
            dfsha_dot_v1_dot_control__pb2.StageManifestPageRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.PageReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SealManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/SealManifest',
            dfsha_dot_v1_dot_control__pb2.SealManifestRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.PageReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/CommitUpload',
            dfsha_dot_v1_dot_control__pb2.CommitUploadRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.CommitResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/AbortUpload',
            dfsha_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.UploadService/GetOperation',
            dfsha_dot_v1_dot_control__pb2.GetOperationRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileAccessServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/dfsha.v1.FileAccessService/Open',
                request_serializer=dfsha_dot_v1_dot_control__pb2.OpenRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.Handle.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/dfsha.v1.FileAccessService/Close',
                request_serializer=dfsha_dot_v1_dot_control__pb2.HandleRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.RenewHandle = channel.unary_unary(
                '/dfsha.v1.FileAccessService/RenewHandle',
                request_serializer=dfsha_dot_v1_dot_control__pb2.HandleRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.Handle.FromString,
                _registered_method=True)
        self.BeginWrite = channel.unary_unary(
                '/dfsha.v1.FileAccessService/BeginWrite',
                request_serializer=dfsha_dot_v1_dot_control__pb2.BeginWriteRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.WritePlan.FromString,
                _registered_method=True)
        self.CommitWrite = channel.unary_unary(
                '/dfsha.v1.FileAccessService/CommitWrite',
                request_serializer=dfsha_dot_v1_dot_control__pb2.CommitWriteRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.CommitResult.FromString,
                _registered_method=True)
        self.AbortWrite = channel.unary_unary(
                '/dfsha.v1.FileAccessService/AbortWrite',
                request_serializer=dfsha_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.Lock = channel.unary_unary(
                '/dfsha.v1.FileAccessService/Lock',
                request_serializer=dfsha_dot_v1_dot_control__pb2.LockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.Fence.FromString,
                _registered_method=True)
        self.Unlock = channel.unary_unary(
                '/dfsha.v1.FileAccessService/Unlock',
                request_serializer=dfsha_dot_v1_dot_control__pb2.FenceRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.RenewLock = channel.unary_unary(
                '/dfsha.v1.FileAccessService/RenewLock',
                request_serializer=dfsha_dot_v1_dot_control__pb2.FenceRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.Fence.FromString,
                _registered_method=True)
        self.ResolveBlocks = channel.unary_unary(
                '/dfsha.v1.FileAccessService/ResolveBlocks',
                request_serializer=dfsha_dot_v1_dot_control__pb2.ResolveBlocksRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_control__pb2.BlockPlan.FromString,
                _registered_method=True)


class FileAccessServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewHandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileAccessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.OpenRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.Handle.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.HandleRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'RenewHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewHandle,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.HandleRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.Handle.SerializeToString,
            ),
            'BeginWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWrite,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.BeginWriteRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.WritePlan.SerializeToString,
            ),
            'CommitWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitWrite,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.CommitWriteRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.CommitResult.SerializeToString,
            ),
            'AbortWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortWrite,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.OperationRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.LockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.Fence.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.FenceRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'RenewLock': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLock,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.FenceRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.Fence.SerializeToString,
            ),
            'ResolveBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveBlocks,
                    request_deserializer=dfsha_dot_v1_dot_control__pb2.ResolveBlocksRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_control__pb2.BlockPlan.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.FileAccessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.FileAccessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileAccessService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/Open',
            dfsha_dot_v1_dot_control__pb2.OpenRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.Handle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/Close',
            dfsha_dot_v1_dot_control__pb2.HandleRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/RenewHandle',
            dfsha_dot_v1_dot_control__pb2.HandleRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.Handle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/BeginWrite',
            dfsha_dot_v1_dot_control__pb2.BeginWriteRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.WritePlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/CommitWrite',
            dfsha_dot_v1_dot_control__pb2.CommitWriteRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.CommitResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/AbortWrite',
            dfsha_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/Lock',
            dfsha_dot_v1_dot_control__pb2.LockRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.Fence.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/Unlock',
            dfsha_dot_v1_dot_control__pb2.FenceRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/RenewLock',
            dfsha_dot_v1_dot_control__pb2.FenceRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.Fence.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.FileAccessService/ResolveBlocks',
            dfsha_dot_v1_dot_control__pb2.ResolveBlocksRequest.SerializeToString,
            dfsha_dot_v1_dot_control__pb2.BlockPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
