# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2
from dfsha.v1 import data_pb2 as dfsha_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutBlock = channel.stream_unary(
                '/dfsha.v1.BlockService/PutBlock',
                request_serializer=dfsha_dot_v1_dot_data__pb2.PutBlockFrame.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
                _registered_method=True)
        self.PatchBlock = channel.stream_unary(
                '/dfsha.v1.BlockService/PatchBlock',
                request_serializer=dfsha_dot_v1_dot_data__pb2.PatchBlockFrame.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_stream(
                '/dfsha.v1.BlockService/GetBlock',
                request_serializer=dfsha_dot_v1_dot_data__pb2.GetBlockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_data__pb2.ReadBlockFrame.FromString,
                _registered_method=True)


class BlockServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.PutBlock,
                    request_deserializer=dfsha_dot_v1_dot_data__pb2.PutBlockFrame.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.SerializeToString,
            ),
            'PatchBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.PatchBlock,
                    request_deserializer=dfsha_dot_v1_dot_data__pb2.PatchBlockFrame.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.SerializeToString,
            ),
            'GetBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=dfsha_dot_v1_dot_data__pb2.GetBlockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_data__pb2.ReadBlockFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.BlockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.BlockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfsha.v1.BlockService/PutBlock',
            dfsha_dot_v1_dot_data__pb2.PutBlockFrame.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfsha.v1.BlockService/PatchBlock',
            dfsha_dot_v1_dot_data__pb2.PatchBlockFrame.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfsha.v1.BlockService/GetBlock',
            dfsha_dot_v1_dot_data__pb2.GetBlockRequest.SerializeToString,
            dfsha_dot_v1_dot_data__pb2.ReadBlockFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplicaServiceStub:
    """Réplicas transportan el contenedor cifrado completo, no plaintext de usuario.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreReplica = channel.stream_unary(
                '/dfsha.v1.ReplicaService/StoreReplica',
                request_serializer=dfsha_dot_v1_dot_data__pb2.ReplicaFrame.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
                _registered_method=True)
        self.GetReplica = channel.unary_stream(
                '/dfsha.v1.ReplicaService/GetReplica',
                request_serializer=dfsha_dot_v1_dot_data__pb2.GetReplicaRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_data__pb2.ReplicaFrame.FromString,
                _registered_method=True)


class ReplicaServiceServicer:
    """Réplicas transportan el contenedor cifrado completo, no plaintext de usuario.
    """

    def StoreReplica(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreReplica': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreReplica,
                    request_deserializer=dfsha_dot_v1_dot_data__pb2.ReplicaFrame.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.SerializeToString,
            ),
            'GetReplica': grpc.unary_stream_rpc_method_handler(
                    servicer.GetReplica,
                    request_deserializer=dfsha_dot_v1_dot_data__pb2.GetReplicaRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_data__pb2.ReplicaFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService:
    """Réplicas transportan el contenedor cifrado completo, no plaintext de usuario.
    """

    @staticmethod
    def StoreReplica(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfsha.v1.ReplicaService/StoreReplica',
            dfsha_dot_v1_dot_data__pb2.ReplicaFrame.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfsha.v1.ReplicaService/GetReplica',
            dfsha_dot_v1_dot_data__pb2.GetReplicaRequest.SerializeToString,
            dfsha_dot_v1_dot_data__pb2.ReplicaFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
