# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import diagnostic_pb2 as dfsha_dot_v1_dot_diagnostic__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/diagnostic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiagnosticServiceStub:
    """Datos sintéticos: estas RPC no son RF1/RF2/RF3 ni almacenan archivos.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/dfsha.v1.DiagnosticService/Health',
                request_serializer=dfsha_dot_v1_dot_diagnostic__pb2.HealthRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamDigest = channel.stream_unary(
                '/dfsha.v1.DiagnosticService/StreamDigest',
                request_serializer=dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticFrame.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.DigestResult.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/dfsha.v1.DiagnosticService/GenerateStream',
                request_serializer=dfsha_dot_v1_dot_diagnostic__pb2.GenerateRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticChunk.FromString,
                _registered_method=True)


class DiagnosticServiceServicer:
    """Datos sintéticos: estas RPC no son RF1/RF2/RF3 ni almacenan archivos.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDigest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagnosticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.HealthRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_diagnostic__pb2.HealthResponse.SerializeToString,
            ),
            'StreamDigest': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamDigest,
                    request_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticFrame.FromString,
                    response_serializer=dfsha_dot_v1_dot_diagnostic__pb2.DigestResult.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=dfsha_dot_v1_dot_diagnostic__pb2.GenerateRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.DiagnosticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.DiagnosticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiagnosticService:
    """Datos sintéticos: estas RPC no son RF1/RF2/RF3 ni almacenan archivos.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.DiagnosticService/Health',
            dfsha_dot_v1_dot_diagnostic__pb2.HealthRequest.SerializeToString,
            dfsha_dot_v1_dot_diagnostic__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDigest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfsha.v1.DiagnosticService/StreamDigest',
            dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticFrame.SerializeToString,
            dfsha_dot_v1_dot_diagnostic__pb2.DigestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfsha.v1.DiagnosticService/GenerateStream',
            dfsha_dot_v1_dot_diagnostic__pb2.GenerateRequest.SerializeToString,
            dfsha_dot_v1_dot_diagnostic__pb2.DiagnosticChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
