# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2
from dfsha.v1 import identity_pb2 as dfsha_dot_v1_dot_identity__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthenticationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/dfsha.v1.AuthenticationService/Login',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.LoginRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.Session.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/dfsha.v1.AuthenticationService/Logout',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.SessionRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.RefreshSession = channel.unary_unary(
                '/dfsha.v1.AuthenticationService/RefreshSession',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.SessionRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.Session.FromString,
                _registered_method=True)


class AuthenticationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.LoginRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.Session.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.SessionRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'RefreshSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshSession,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.SessionRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.AuthenticationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.AuthenticationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthenticationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.AuthenticationService/Login',
            dfsha_dot_v1_dot_identity__pb2.LoginRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.AuthenticationService/Logout',
            dfsha_dot_v1_dot_identity__pb2.SessionRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.AuthenticationService/RefreshSession',
            dfsha_dot_v1_dot_identity__pb2.SessionRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IdentityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/dfsha.v1.IdentityService/CreateUser',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.User.FromString,
                _registered_method=True)
        self.SetUser = channel.unary_unary(
                '/dfsha.v1.IdentityService/SetUser',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.SetUserRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.User.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/dfsha.v1.IdentityService/CreateGroup',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.Group.FromString,
                _registered_method=True)
        self.SetGroupMembers = channel.unary_unary(
                '/dfsha.v1.IdentityService/SetGroupMembers',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.SetGroupMembersRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_identity__pb2.Group.FromString,
                _registered_method=True)
        self.GetAcl = channel.unary_unary(
                '/dfsha.v1.IdentityService/GetAcl',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.GetAclRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.Acl.FromString,
                _registered_method=True)
        self.SetAcl = channel.unary_unary(
                '/dfsha.v1.IdentityService/SetAcl',
                request_serializer=dfsha_dot_v1_dot_identity__pb2.SetAclRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)


class IdentityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGroupMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAcl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAcl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.CreateUserRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.User.SerializeToString,
            ),
            'SetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUser,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.SetUserRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.User.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.CreateGroupRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.Group.SerializeToString,
            ),
            'SetGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGroupMembers,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.SetGroupMembersRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_identity__pb2.Group.SerializeToString,
            ),
            'GetAcl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAcl,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.GetAclRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.Acl.SerializeToString,
            ),
            'SetAcl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAcl,
                    request_deserializer=dfsha_dot_v1_dot_identity__pb2.SetAclRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/CreateUser',
            dfsha_dot_v1_dot_identity__pb2.CreateUserRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/SetUser',
            dfsha_dot_v1_dot_identity__pb2.SetUserRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/CreateGroup',
            dfsha_dot_v1_dot_identity__pb2.CreateGroupRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.Group.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/SetGroupMembers',
            dfsha_dot_v1_dot_identity__pb2.SetGroupMembersRequest.SerializeToString,
            dfsha_dot_v1_dot_identity__pb2.Group.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/GetAcl',
            dfsha_dot_v1_dot_identity__pb2.GetAclRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.Acl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.IdentityService/SetAcl',
            dfsha_dot_v1_dot_identity__pb2.SetAclRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
