# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2
from dfsha.v1 import namespace_pb2 as dfsha_dot_v1_dot_namespace__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/namespace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NamespaceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/dfsha.v1.NamespaceService/List',
                request_serializer=dfsha_dot_v1_dot_namespace__pb2.ListRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_namespace__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/dfsha.v1.NamespaceService/Stat',
                request_serializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_namespace__pb2.Entry.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/dfsha.v1.NamespaceService/Mkdir',
                request_serializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_namespace__pb2.Entry.FromString,
                _registered_method=True)
        self.Rmdir = channel.unary_unary(
                '/dfsha.v1.NamespaceService/Rmdir',
                request_serializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/dfsha.v1.NamespaceService/Remove',
                request_serializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)


class NamespaceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rmdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamespaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=dfsha_dot_v1_dot_namespace__pb2.ListRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_namespace__pb2.ListResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_namespace__pb2.Entry.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_namespace__pb2.Entry.SerializeToString,
            ),
            'Rmdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Rmdir,
                    request_deserializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=dfsha_dot_v1_dot_namespace__pb2.PathRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.NamespaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.NamespaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamespaceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NamespaceService/List',
            dfsha_dot_v1_dot_namespace__pb2.ListRequest.SerializeToString,
            dfsha_dot_v1_dot_namespace__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NamespaceService/Stat',
            dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
            dfsha_dot_v1_dot_namespace__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NamespaceService/Mkdir',
            dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
            dfsha_dot_v1_dot_namespace__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rmdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NamespaceService/Rmdir',
            dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NamespaceService/Remove',
            dfsha_dot_v1_dot_namespace__pb2.PathRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
