# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfsha/v1/namespace.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dfsha/v1/namespace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x66sha/v1/namespace.proto\x12\x08\x64\x66sha.v1\x1a\x15\x64\x66sha/v1/common.proto\"Y\n\x0bPathRequest\x12)\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x18.dfsha.v1.RequestContext\x12\x1f\n\x04path\x18\x02 \x01(\x0b\x32\x11.dfsha.v1.PathRef\"~\n\x0bListRequest\x12)\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x18.dfsha.v1.RequestContext\x12\x1f\n\x04path\x18\x02 \x01(\x0b\x32\x11.dfsha.v1.PathRef\x12#\n\x04page\x18\x03 \x01(\x0b\x32\x15.dfsha.v1.PageRequest\"\x9b\x01\n\x05\x45ntry\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\"\n\x04kind\x18\x03 \x01(\x0e\x32\x14.dfsha.v1.ObjectKind\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04\x12\x10\n\x08revision\x18\x05 \x01(\x04\x12\'\n\x08snapshot\x18\x06 \x01(\x0b\x32\x15.dfsha.v1.SnapshotRef\"a\n\x0cListResponse\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.dfsha.v1.Entry\x12\x13\n\x0bnext_cursor\x18\x02 \x01(\t\x12\x1a\n\x12\x64irectory_revision\x18\x03 \x01(\x04\x32\x9f\x02\n\x10NamespaceService\x12\x35\n\x04List\x12\x15.dfsha.v1.ListRequest\x1a\x16.dfsha.v1.ListResponse\x12.\n\x04Stat\x12\x15.dfsha.v1.PathRequest\x1a\x0f.dfsha.v1.Entry\x12/\n\x05Mkdir\x12\x15.dfsha.v1.PathRequest\x1a\x0f.dfsha.v1.Entry\x12\x38\n\x05Rmdir\x12\x15.dfsha.v1.PathRequest\x1a\x18.dfsha.v1.MutationResult\x12\x39\n\x06Remove\x12\x15.dfsha.v1.PathRequest\x1a\x18.dfsha.v1.MutationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfsha.v1.namespace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATHREQUEST']._serialized_start=61
  _globals['_PATHREQUEST']._serialized_end=150
  _globals['_LISTREQUEST']._serialized_start=152
  _globals['_LISTREQUEST']._serialized_end=278
  _globals['_ENTRY']._serialized_start=281
  _globals['_ENTRY']._serialized_end=436
  _globals['_LISTRESPONSE']._serialized_start=438
  _globals['_LISTRESPONSE']._serialized_end=535
  _globals['_NAMESPACESERVICE']._serialized_start=538
  _globals['_NAMESPACESERVICE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
