# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfsha.v1 import common_pb2 as dfsha_dot_v1_dot_common__pb2
from dfsha.v1 import nodes_pb2 as dfsha_dot_v1_dot_nodes__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfsha/v1/nodes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeRegistryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/dfsha.v1.NodeRegistryService/RegisterNode',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.NodeLease.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dfsha.v1.NodeRegistryService/Heartbeat',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.NodeLease.FromString,
                _registered_method=True)
        self.BlockReport = channel.unary_unary(
                '/dfsha.v1.NodeRegistryService/BlockReport',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.BlockReportRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ReportDurable = channel.unary_unary(
                '/dfsha.v1.NodeRegistryService/ReportDurable',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.ReportDurableRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ReportTask = channel.unary_unary(
                '/dfsha.v1.NodeRegistryService/ReportTask',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.ReportTaskRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
                _registered_method=True)


class NodeRegistryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDurable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.RegisterNodeRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.NodeLease.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.HeartbeatRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.NodeLease.SerializeToString,
            ),
            'BlockReport': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockReport,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.BlockReportRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'ReportDurable': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDurable,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.ReportDurableRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
            'ReportTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTask,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.ReportTaskRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.MutationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.NodeRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.NodeRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeRegistryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NodeRegistryService/RegisterNode',
            dfsha_dot_v1_dot_nodes__pb2.RegisterNodeRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.NodeLease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NodeRegistryService/Heartbeat',
            dfsha_dot_v1_dot_nodes__pb2.HeartbeatRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.NodeLease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NodeRegistryService/BlockReport',
            dfsha_dot_v1_dot_nodes__pb2.BlockReportRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDurable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NodeRegistryService/ReportDurable',
            dfsha_dot_v1_dot_nodes__pb2.ReportDurableRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.NodeRegistryService/ReportTask',
            dfsha_dot_v1_dot_nodes__pb2.ReportTaskRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InternalAuthorizationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorizeBlock = channel.unary_unary(
                '/dfsha.v1.InternalAuthorizationService/AuthorizeBlock',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizeBlockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.FromString,
                _registered_method=True)
        self.AuthorizeInternal = channel.unary_unary(
                '/dfsha.v1.InternalAuthorizationService/AuthorizeInternal',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizeInternalRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.FromString,
                _registered_method=True)


class InternalAuthorizationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AuthorizeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeInternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalAuthorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorizeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeBlock,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizeBlockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.SerializeToString,
            ),
            'AuthorizeInternal': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeInternal,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizeInternalRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.InternalAuthorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.InternalAuthorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalAuthorizationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthorizeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.InternalAuthorizationService/AuthorizeBlock',
            dfsha_dot_v1_dot_nodes__pb2.AuthorizeBlockRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeInternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.InternalAuthorizationService/AuthorizeInternal',
            dfsha_dot_v1_dot_nodes__pb2.AuthorizeInternalRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.AuthorizationDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageAdministrationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyReceipt = channel.unary_unary(
                '/dfsha.v1.StorageAdministrationService/VerifyReceipt',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.VerifyReceiptRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
                _registered_method=True)
        self.ReplicateBlock = channel.unary_unary(
                '/dfsha.v1.StorageAdministrationService/ReplicateBlock',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.ReplicateBlockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/dfsha.v1.StorageAdministrationService/GetTask',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.DeleteRetiredBlock = channel.unary_unary(
                '/dfsha.v1.StorageAdministrationService/DeleteRetiredBlock',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.DeleteRetiredBlockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
                _registered_method=True)


class StorageAdministrationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def VerifyReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRetiredBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageAdministrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyReceipt,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.VerifyReceiptRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_common__pb2.DurableReceipt.SerializeToString,
            ),
            'ReplicateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateBlock,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.ReplicateBlockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.SerializeToString,
            ),
            'DeleteRetiredBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRetiredBlock,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.DeleteRetiredBlockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.StorageAdministrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.StorageAdministrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageAdministrationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerifyReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.StorageAdministrationService/VerifyReceipt',
            dfsha_dot_v1_dot_nodes__pb2.VerifyReceiptRequest.SerializeToString,
            dfsha_dot_v1_dot_common__pb2.DurableReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.StorageAdministrationService/ReplicateBlock',
            dfsha_dot_v1_dot_nodes__pb2.ReplicateBlockRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.StorageAdministrationService/GetTask',
            dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRetiredBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.StorageAdministrationService/DeleteRetiredBlock',
            dfsha_dot_v1_dot_nodes__pb2.DeleteRetiredBlockRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClusterAdministrationServiceStub:
    """API administrativa de control por TLS + sesión admin, nunca identidad de nodo.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNodes = channel.unary_unary(
                '/dfsha.v1.ClusterAdministrationService/ListNodes',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.ClusterQuery.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.NodeStatusPage.FromString,
                _registered_method=True)
        self.CopyBlock = channel.unary_unary(
                '/dfsha.v1.ClusterAdministrationService/CopyBlock',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.CopyBlockRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.CopyStatus = channel.unary_unary(
                '/dfsha.v1.ClusterAdministrationService/CopyStatus',
                request_serializer=dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
                _registered_method=True)


class ClusterAdministrationServiceServicer:
    """API administrativa de control por TLS + sesión admin, nunca identidad de nodo.
    """

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterAdministrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.ClusterQuery.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.NodeStatusPage.SerializeToString,
            ),
            'CopyBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyBlock,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.CopyBlockRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.SerializeToString,
            ),
            'CopyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyStatus,
                    request_deserializer=dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.FromString,
                    response_serializer=dfsha_dot_v1_dot_nodes__pb2.TaskStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.v1.ClusterAdministrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.v1.ClusterAdministrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterAdministrationService:
    """API administrativa de control por TLS + sesión admin, nunca identidad de nodo.
    """

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.ClusterAdministrationService/ListNodes',
            dfsha_dot_v1_dot_nodes__pb2.ClusterQuery.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.NodeStatusPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.ClusterAdministrationService/CopyBlock',
            dfsha_dot_v1_dot_nodes__pb2.CopyBlockRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.v1.ClusterAdministrationService/CopyStatus',
            dfsha_dot_v1_dot_nodes__pb2.GetTaskRequest.SerializeToString,
            dfsha_dot_v1_dot_nodes__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
