# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfsha/_vendor/etcd/api/authpb/auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dfsha/_vendor/etcd/api/authpb/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfsha._vendor.gogoproto import gogo_pb2 as dfsha_dot___vendor_dot_gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dfsha/_vendor/etcd/api/authpb/auth.proto\x12\x06\x61uthpb\x1a\"dfsha/_vendor/gogoproto/gogo.proto\"%\n\x0eUserAddOptions\x12\x13\n\x0bno_password\x18\x01 \x01(\x08\"^\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\x12\r\n\x05roles\x18\x03 \x03(\t\x12\'\n\x07options\x18\x04 \x01(\x0b\x32\x16.authpb.UserAddOptions\"\x83\x01\n\nPermission\x12)\n\x08permType\x18\x01 \x01(\x0e\x32\x17.authpb.Permission.Type\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x11\n\trange_end\x18\x03 \x01(\x0c\"*\n\x04Type\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\r\n\tREADWRITE\x10\x02\"?\n\x04Role\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12)\n\rkeyPermission\x18\x02 \x03(\x0b\x32\x12.authpb.PermissionB3Z\x1dgo.etcd.io/etcd/api/v3/authpb\xc8\xe1\x1e\x00\xd0\xe1\x1e\x00\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\xe0\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfsha._vendor.etcd.api.authpb.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035go.etcd.io/etcd/api/v3/authpb\310\341\036\000\320\341\036\000\310\342\036\001\320\342\036\001\340\342\036\001'
  _globals['_USERADDOPTIONS']._serialized_start=88
  _globals['_USERADDOPTIONS']._serialized_end=125
  _globals['_USER']._serialized_start=127
  _globals['_USER']._serialized_end=221
  _globals['_PERMISSION']._serialized_start=224
  _globals['_PERMISSION']._serialized_end=355
  _globals['_PERMISSION_TYPE']._serialized_start=313
  _globals['_PERMISSION_TYPE']._serialized_end=355
  _globals['_ROLE']._serialized_start=357
  _globals['_ROLE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
